[build]
publish = "exampleSite/public"
command = "cd exampleSite && hugo --themesDir=../.. --baseURL $URL"

[build.environment]
HUGO_VERSION = "0.79.1"
HUGO_THEME = "rep"

[context.deploy-preview]
command = "cd exampleSite &&  hugo --themesDir=../.. --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"
